[[main]]
none = "none"

[[main]]
name = "Blog"
pageRef = "posts"
identifier = "hFLLmtecPq"
weight = 9_999

[[main]]
name = "CTFs"
pageRef = "ctfs"
identifier = "X01TxeUmpl"
weight = 9_999

[[footer]]
none = "none"
